# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f08d8ec516494d284965fe6d8b0361f15c138d66ec38a9a131d12e59925f04c96401f70dfbeedaeddec8fb87210fea4259b3af554333df5ae83f212149d2e84

test:
  secret_key_base: 3c49190967a6f95e1347061a08a39f53347a2977573a41d3358883f4338fada90ee5797e761f24ff7e15bab1ac5c319fd5e61031819bb057d345be3ee71ecfde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
